### PR TITLE
Create Merge_sorting.c

### PR DESCRIPTION
**Pull request by Arka0101**

### CODE REVIEW

**Comment by Ekj0t** [comment]
I'm new to opensource, can I work on this issue and is this issue accepted for hacktoberfest?

**Comment by electrongonewild** [comment]
@Ekj0t you can go through the Readme.md once and if you are interested in electronics/automation and code related to that, then you can contribute in this repository.

**Comment by Ekj0t** [comment]
@electrongonewild 2what are some automation/electronics on which I can contribute. Can you tell me some topics?

**Comment by electrongonewild** [comment]
@Ekj0t You can start with any hardware interfacing with microcontrollers. For getting started you can start with arduino, it is an open hardware development board.

**Comment by Ekj0t** [comment]
@electrongonewild What languages are needed in this.

**Pull request closed without merging**
